version: "3.0"

services:

  elasticsearch:
    container_name: elasticsearch-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"      
    networks:
      - elastic
    ports:
      - 9200:9200

  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-container:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
    container_name: logstash-container
    image: docker.elastic.co/logstash/logstash:8.0.0    
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:      
      - ELASTICSEARCH_HOSTS=http://elasticsearch-container:9200
    volumes:      
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge